{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3a016917-d5a0-46b9-b4e4-0b52531607be",
   "metadata": {},
   "outputs": [],
   "source": [
    "from tkinter import ttk\n",
    "from tkinter import *\n",
    "from tkinter.ttk import Combobox\n",
    "from PIL import Image,ImageTk\n",
    "from tkinter import messagebox,filedialog\n",
    "import sqlite3\n",
    "import os\n",
    "import shutil\n",
    "\n",
    "\n",
    "\n",
    "win=Tk()\n",
    "win.state(\"zoomed\")\n",
    "win.configure(bg=\"Silver\")\n",
    "title=Label(win,text=\"BANK ACCOUNT SIMULATION\",font=('cambria',38,'bold','underline'),bg=\"silver\",fg=\"navy blue\")\n",
    "title.pack()\n",
    "\n",
    "logo_pic=ImageTk.PhotoImage(Image.open(\"images/231.jpg\").resize((115,100)),master=win)\n",
    "lbl_logo=Label(win,image=logo_pic)\n",
    "lbl_logo.place(relx=0,rely=0)\n",
    "\n",
    "\n",
    "default_pic=ImageTk.PhotoImage(Image.open(\"images/profilepic.jpg\").resize((125,140)),master=win)\n",
    "\n",
    "\n",
    "def home_screen():\n",
    "    frm=Frame(win)\n",
    "    frm.configure(bg=\"powder blue\")\n",
    "    frm.place(x=0,y=100,relwidth=1,relheight=.9)\n",
    "    \n",
    "    def newuser():\n",
    "        frm.destroy()\n",
    "        newuser_screen()\n",
    "    \n",
    "    def forgot():\n",
    "        frm.destroy()\n",
    "        forgot_pass_screen()\n",
    "    \n",
    "    def login():\n",
    "        acn=acn_entry.get()\n",
    "        pwd=pass_entry.get()\n",
    "        if(len(acn)==0 or len(pwd)==0):\n",
    "            messagebox.showerror(\"Validation\",\"Please fill both fields\")\n",
    "        elif(not acn.isdigit()):\n",
    "            messagebox.showerror(\"Validation\",\"Account No must be numeric\")\n",
    "        else:\n",
    "            con=sqlite3.connect(database=\"bank.sqlite\")\n",
    "            cur=con.cursor()\n",
    "            cur.execute(\"select * from users where acn=? and pass=?\",(acn,pwd))\n",
    "            global tup\n",
    "            tup=cur.fetchone()\n",
    "            if(tup==None):\n",
    "                messagebox.showerror(\"Login\",\"Invalid Account No/Password!!\")\n",
    "            else:\n",
    "                frm.destroy()\n",
    "                login_screen()\n",
    "     \n",
    "    def reset():\n",
    "        acn_entry.delete(0,\"end\")\n",
    "        pass_entry.delete(0,\"end\")\n",
    "        acn_entry.focus()\n",
    "        \n",
    "    lbl_acn=Label(frm,text=\"Account No\",font=('cambria',15,'bold'),bg='powder blue')\n",
    "    lbl_acn.place(relx=.35,rely=.1)\n",
    "    \n",
    "    acn_entry=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "    acn_entry.place(relx=.43,rely=.1)\n",
    "    \n",
    "    lbl_pass=Label(frm,text=\"Password\",font=('cambria',15,'bold'),bg='powder blue')\n",
    "    lbl_pass.place(relx=.35,rely=.2)\n",
    "    \n",
    "    pass_entry=Entry(frm,font=('cambria',15,'bold'),bd=3,show=\"*\")\n",
    "    pass_entry.place(relx=.43,rely=.2)\n",
    "    \n",
    "    login_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Login\",width=12,command=login)\n",
    "    login_btn.place(relx=.3,rely=.35)\n",
    "    \n",
    "    reset_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Reset\",width=12,command=reset)\n",
    "    reset_btn.place(relx=.43,rely=.35)\n",
    "    \n",
    "    lbl_newuser=Label(frm,text=\"If You Don't Have An Account In Bank\",font=('cambria',15,'italic','bold',\"underline\"),bg='powder blue')\n",
    "    lbl_newuser.place(relx=.3,rely=.51)\n",
    "    newuser_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"New User\",width=13,bg=\"orange\",command=newuser)\n",
    "    newuser_btn.place(relx=.56,rely=.5)\n",
    "    \n",
    "    fp_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Forgot Password\",width=13,command=forgot)\n",
    "    fp_btn.place(relx=.56,rely=.35)\n",
    "    \n",
    "    lbl_newuser=Label(frm,text= \"Created By Ansh D Mishra\" ,font=('cambria',10,'italic','bold',\"underline\"),fg= \"red\", bg='powder blue')\n",
    "    lbl_newuser.place(relx=.015,rely=.9)\n",
    "    \n",
    "    \n",
    "    \n",
    "        \n",
    "def newuser_screen():\n",
    "    frm=Frame(win)\n",
    "    frm.configure(bg=\"powder blue\")\n",
    "    frm.place(x=0,y=100,relwidth=1,relheight=.9)\n",
    "\n",
    "    def back():\n",
    "        frm.destroy()\n",
    "        home_screen()  \n",
    "        \n",
    "    def submit():\n",
    "        name=name_entry.get()\n",
    "        pwd=pass_entry.get()\n",
    "        email=email_entry.get()\n",
    "        mob=mob_entry.get()\n",
    "        acntype=cb_type.get()\n",
    "        bal=0\n",
    "        \n",
    "        con=sqlite3.connect(database=\"bank.sqlite\")\n",
    "        cur=con.cursor()\n",
    "        cur.execute(\"insert into users(name,pass,email,mob,type,bal) values(?,?,?,?,?,?)\",(name,pwd,email,mob,acntype,bal))\n",
    "        con.commit()\n",
    "        con.close()\n",
    "        \n",
    "        con=sqlite3.connect(database=\"bank.sqlite\")\n",
    "        cur=con.cursor()\n",
    "        cur.execute(\"select max(acn) from users\")\n",
    "        tup=cur.fetchone()\n",
    "        messagebox.showinfo(\"Account\",f\"Account opened with ACN:{tup[0]}\")\n",
    "        con.close()\n",
    "        \n",
    "    back_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Back\",width=10, command=back)\n",
    "    back_btn.place(relx=0,rely=0.01)\n",
    "    \n",
    "    lbl_name=Label(frm,text=\"Name\",font=('cambria',15,'bold'),bg='powder blue')\n",
    "    lbl_name.place(relx=.3,rely=.1)\n",
    "    \n",
    "    name_entry=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "    name_entry.place(relx=.4,rely=.1)\n",
    "    \n",
    "    lbl_pass=Label(frm,text=\"Pass\",font=('cambria',15,'bold'),bg='powder blue')\n",
    "    lbl_pass.place(relx=.3,rely=.2)\n",
    "    \n",
    "    pass_entry=Entry(frm,font=('cambria',15,'bold'),bd=3,show=\"*\")\n",
    "    pass_entry.place(relx=.4,rely=.2)\n",
    "    \n",
    "    lbl_email=Label(frm,text=\"Email\",font=('cambria',15,'bold'),bg='powder blue')\n",
    "    lbl_email.place(relx=.3,rely=.3)\n",
    "    \n",
    "    email_entry=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "    email_entry.place(relx=.4,rely=.3)\n",
    "    \n",
    "    lbl_mob=Label(frm,text=\"Mob\",font=('cambria',15,'bold'),bg='powder blue')\n",
    "    lbl_mob.place(relx=.3,rely=.4)\n",
    "    \n",
    "    mob_entry=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "    mob_entry.place(relx=.4,rely=.4)\n",
    "    \n",
    "    lbl_type=Label(frm,text=\"Type\",font=('cambria',15,'bold'),bg='powder blue')\n",
    "    lbl_type.place(relx=.3,rely=.5)\n",
    "    \n",
    "    cb_type=Combobox(frm,values=['Saving','Current'],font=('cambria',15,'bold'))\n",
    "    cb_type.place(relx=.4,rely=.5)\n",
    "    cb_type.current(0)\n",
    "    \n",
    "    sub_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Submit\",width=10,command=submit)\n",
    "    sub_btn.place(relx=.89,rely=.84)\n",
    "    \n",
    "    \n",
    "def forgot_pass_screen():\n",
    "    frm=Frame(win)\n",
    "    frm.configure(bg=\"powder blue\")\n",
    "    frm.place(x=0,y=100,relwidth=1,relheight=.9)\n",
    "\n",
    "    def back():\n",
    "        frm.destroy()\n",
    "        home_screen()  \n",
    "        \n",
    "    def submit():\n",
    "        acn=acn_entry.get()\n",
    "        email=email_entry.get()\n",
    "        mob=mob_entry.get()\n",
    "        con=sqlite3.connect(database=\"bank.sqlite\")\n",
    "        cur=con.cursor()\n",
    "        cur.execute(\"select pass from users where acn=? and email=? and mob=?\",(acn,email,mob))\n",
    "        p=cur.fetchone()\n",
    "        con.close()\n",
    "        \n",
    "        if(p==None):\n",
    "                messagebox.showerror(\"Recovery\",\"Details not found\")\n",
    "        else:\n",
    "            messagebox.showinfo(\"Recovery\",f\"Your pass:{p[0]}\")\n",
    "        \n",
    "    back_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Back\",width=10,command=back)\n",
    "    back_btn.place(relx=0,rely=0.01)\n",
    "    \n",
    "    lbl_acn=Label(frm,text=\"Account No\",font=('cambria',15,'bold'),bg='powder blue')\n",
    "    lbl_acn.place(relx=.3,rely=.2)\n",
    "    \n",
    "    acn_entry=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "    acn_entry.place(relx=.4,rely=.2)\n",
    "    \n",
    "    lbl_email=Label(frm,text=\"Email ID\",font=('cambria',15,'bold'),bg='powder blue')\n",
    "    lbl_email.place(relx=.3,rely=.3)\n",
    "    \n",
    "    email_entry=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "    email_entry.place(relx=.4,rely=.3)\n",
    "    \n",
    "    lbl_mob=Label(frm,text=\"Mobile No\",font=('cambria',15,'bold'),bg='powder blue')\n",
    "    lbl_mob.place(relx=.3,rely=.4)\n",
    "    \n",
    "    mob_entry=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "    mob_entry.place(relx=.4,rely=.4)\n",
    "    \n",
    "    sub_btn=Button(frm,font=('cambria',15,'bold'),bd=5,text=\"Submit\",width=10,command=submit)\n",
    "    sub_btn.place(relx=.89,rely=.84)\n",
    "    \n",
    "    \n",
    "def login_screen():\n",
    "    frm=Frame(win)\n",
    "    frm.configure(bg=\"powder blue\")\n",
    "    frm.place(x=0,y=100,relwidth=1,relheight=.9)\n",
    "    \n",
    "    def logout():\n",
    "        frm.destroy()\n",
    "        home_screen()  \n",
    "        \n",
    "    def details():\n",
    "        frm.destroy()\n",
    "        details_screen()\n",
    "     \n",
    "    def withdraw():\n",
    "        frm.destroy()\n",
    "        withdraw_screen()\n",
    "        \n",
    "    def deposit():\n",
    "        frm.destroy()\n",
    "        deposit_screen()\n",
    "    \n",
    "    def txn():\n",
    "        frm.destroy()\n",
    "        txnhistory_screen()\n",
    "        \n",
    "        \n",
    "    def update():\n",
    "        frm.destroy()\n",
    "        updateprofile_screen()\n",
    "    \n",
    "    def update_pic():\n",
    "        path=filedialog.askopenfilename()\n",
    "        index=path.rindex(\".\")\n",
    "        ext=path[index+1:]\n",
    "        shutil.copy(path,f\"images/{tup[0]}.{ext}\")\n",
    "        \n",
    "        pic=ImageTk.PhotoImage(Image.open(f\"images/{tup[0]}.{ext}\").resize((125,140)),master=win)\n",
    "        \n",
    "    logout_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Logout\",width=10,command=logout)\n",
    "    logout_btn.place(relx=.89,rely=0)\n",
    "    \n",
    "    lbl_wel=Label(frm,text=f\"Login Successfully!....Welcome,\\t{tup[1]}\",font=('cambria',12,'bold'),bg='powder blue', fg=\"green\")\n",
    "    lbl_wel.place(relx=0,rely=0)\n",
    "     \n",
    "    \n",
    "    lbl_pic=Label(frm,image=default_pic)\n",
    "    lbl_pic.place(relx=0,rely=.06)\n",
    "    \n",
    "    imgs=os.listdir(\"images\")\n",
    "    \n",
    "    for img in imgs:\n",
    "        if(img.startswith(str(tup[0]))):\n",
    "            pic=ImageTk.PhotoImage(Image.open(f\"images/{img}\").resize((125,140)),master=win)\n",
    "            lbl_pic.configure(image=pic)\n",
    "            lbl_pic.image=pic   \n",
    "            \n",
    "    def update_pic():\n",
    "        path=filedialog.askopenfilename()\n",
    "        index=path.rindex(\".\")\n",
    "        ext=path[index+1:]\n",
    "        shutil.copy(path,f\"images/{tup[0]}.{ext}\")\n",
    "        \n",
    "        default_pic=ImageTk.PhotoImage(Image.open(f\"images/{tup[0]}.{ext}\").resize((125,140)),master=win)\n",
    "        lbl_pic.configure(image=default_pic)\n",
    "        lbl_pic.image=default_pic\n",
    "        \n",
    "    details_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Details\",width=12,command=details)\n",
    "    details_btn.place(relx=.3,rely=.1)\n",
    "    \n",
    "    pic_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Update Picture\",width=12,command=update_pic)\n",
    "    pic_btn.place(relx=.5,rely=.1)\n",
    "    \n",
    "    deposit_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Deposit\",width=12,command=deposit)\n",
    "    deposit_btn.place(relx=.3,rely=.25)\n",
    "    \n",
    "    withdraw_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Withdraw\",width=12,command=withdraw)\n",
    "    withdraw_btn.place(relx=.5,rely=.25)\n",
    "    \n",
    "    update_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Update Profile\",width=12,command=update)\n",
    "    update_btn.place(relx=.3,rely=.4)\n",
    "    \n",
    "    hist_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Txn History\",width=12,command=txn)\n",
    "    hist_btn.place(relx=.5,rely=.4)\n",
    "\n",
    "    \n",
    "def details_screen():\n",
    "    frm=Frame(win)\n",
    "    frm.configure(bg=\"powder blue\")\n",
    "    frm.place(x=0,y=100,relwidth=1,relheight=.9)\n",
    "   \n",
    "    \n",
    "    def logout():\n",
    "        frm.destroy()\n",
    "        home_screen()  \n",
    "        \n",
    "    def back():\n",
    "        frm.destroy()\n",
    "        login_screen()\n",
    "    logout_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Logout\",width=10,command=logout)\n",
    "    logout_btn.place(relx=.89,rely=0)\n",
    "    \n",
    "    lbl_wel=Label(frm,text=f\"Welcome,{tup[1]}\",font=('cambria',12,'bold'),bg='powder blue')\n",
    "    lbl_wel.place(relx=0,rely=0)\n",
    "    \n",
    "    lbl_pic=Label(frm,image=default_pic)\n",
    "    lbl_pic.place(relx=0,rely=.06)\n",
    "    \n",
    "    lbl_title=Label(frm,text=\"Account Details\",fg='Navy Blue',font=('cambria',25,'bold','underline'),bg='powder blue')\n",
    "    lbl_title.pack()\n",
    "    \n",
    "    con=sqlite3.connect(database=\"bank.sqlite\")\n",
    "    cur=con.cursor()\n",
    "    cur.execute(\"select * from users where acn=? and pass=?\",(tup[0],tup[2]))\n",
    "    row=cur.fetchone()\n",
    "    \n",
    "    data= f\"\"\" \n",
    "    ACN: \\t\\t {row[0]} \n",
    "    Name: \\t\\t{row[1]}\n",
    "    Pass: \\t\\t{row[2]}\n",
    "    Email: \\t\\t{row[3]}\n",
    "    Mob: \\t\\t{row[4]}\n",
    "    Type: \\t\\t{row[5]}\n",
    "    Bal: \\t\\t{row[6]}\n",
    "    \"\"\"\n",
    "    \n",
    "    details_lbl=Label(frm,text=data,bg=\"powder blue\",fg=\"Navy Blue\",font=('cambria',15))\n",
    "    details_lbl.place(relx=.2,rely=.2)\n",
    "    \n",
    "    back_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Back\",width=10, command=back)\n",
    "    back_btn.place(relx=0,rely=.3)\n",
    "    \n",
    "    \n",
    "\n",
    "def withdraw_screen():\n",
    "    frm=Frame(win)\n",
    "    frm.configure(bg=\"powder blue\")\n",
    "    frm.place(x=0,y=100,relwidth=1,relheight=.9)\n",
    "    \n",
    "    def logout():\n",
    "        frm.destroy()\n",
    "        home_screen()  \n",
    "    def back():\n",
    "        frm.destroy()\n",
    "        login_screen()\n",
    "    logout_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Logout\",width=10,command=logout)\n",
    "    logout_btn.place(relx=.89,rely=0)\n",
    "    \n",
    "    lbl_wel=Label(frm,text=f\"Welcome,{tup[1]}\",font=('cambria',12,'bold'),bg='powder blue')\n",
    "    lbl_wel.place(relx=0,rely=0)\n",
    "    \n",
    "    lbl_pic=Label(frm,image=default_pic)\n",
    "    lbl_pic.place(relx=0,rely=.06)\n",
    "    \n",
    "    imgs=os.listdir(\"images\")\n",
    "    \n",
    "    for img in imgs:\n",
    "        if(img.startswith(str(tup[0]))):\n",
    "            pic=ImageTk.PhotoImage(Image.open(f\"images/{img}\").resize((125,140)),master=win)\n",
    "            lbl_pic.configure(image=pic)\n",
    "            lbl_pic.image=pic\n",
    "            \n",
    "    lbl_title=Label(frm,text=\"Withdraw Screen\",fg='Green',font=('cambria',25,'bold','underline'),bg='powder blue')\n",
    "    lbl_title.pack()\n",
    "    \n",
    "    back_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Back\",width=10, command=back)\n",
    "    back_btn.place(relx=0,rely=.3)\n",
    "    \n",
    "    def submit():\n",
    "        amt=int(amt_entry.get())\n",
    "        con=sqlite3.connect(database=\"bank.sqlite\")\n",
    "        cur=con.cursor()\n",
    "        cur.execute(\"select bal from users where acn=?\",(tup[0],))\n",
    "        t=cur.fetchone()\n",
    "        bal=t[0]\n",
    "        if(bal>amt):\n",
    "            \n",
    "            bal=bal-amt\n",
    "            con.close()\n",
    "\n",
    "            con=sqlite3.connect(database=\"bank.sqlite\")\n",
    "            cur=con.cursor()\n",
    "            cur.execute(\"update users set bal=? where acn=?\",(bal,tup[0]))\n",
    "            con.commit()\n",
    "            con.close()\n",
    "            messagebox.showinfo(\"Deposit\",\"Amount withdrawn\")\n",
    "\n",
    "            con=sqlite3.connect(database=\"bank.sqlite\")\n",
    "            cur=con.cursor()\n",
    "            from datetime import datetime\n",
    "            dt=str(datetime.now())\n",
    "            cur.execute(\"insert into txn values(?,?,?,?,?)\",(tup[0],dt,amt,\"Debit\",bal))\n",
    "            con.commit()\n",
    "            con.close()\n",
    "        else:\n",
    "            messagebox.showerror(\"Withdraw\",\"Insufficient Bal\")\n",
    "\n",
    "    lbl_amt=Label(frm,text=\"Amount\",font=('cambria',15,'bold'),bg='powder blue')\n",
    "    lbl_amt.place(relx=.3,rely=.2)\n",
    "    \n",
    "    amt_entry=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "    amt_entry.place(relx=.4,rely=.2)\n",
    "    \n",
    "    sub_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Submit\",width=10,command=submit)\n",
    "    sub_btn.place(relx=.89,rely=.84)\n",
    "    \n",
    "def deposit_screen():\n",
    "    frm=Frame(win)\n",
    "    frm.configure(bg=\"powder blue\")\n",
    "    frm.place(x=0,y=100,relwidth=1,relheight=.9)\n",
    "    \n",
    "    def logout():\n",
    "        frm.destroy()\n",
    "        home_screen()  \n",
    "    def back():\n",
    "        frm.destroy()\n",
    "        login_screen()\n",
    "        \n",
    "    def submit():\n",
    "        amt=int(amt_entry.get())\n",
    "        con=sqlite3.connect(database=\"bank.sqlite\")\n",
    "        cur=con.cursor()\n",
    "        cur.execute(\"select bal from users where acn=?\",(tup[0],))\n",
    "        t=cur.fetchone()\n",
    "        bal=t[0]\n",
    "        bal=bal+amt\n",
    "        con.close()\n",
    "        \n",
    "        con=sqlite3.connect(database=\"bank.sqlite\")\n",
    "        cur=con.cursor()\n",
    "        cur.execute(\"update users set bal=? where acn=?\",(bal,tup[0]))\n",
    "        con.commit()\n",
    "        con.close()\n",
    "        messagebox.showinfo(\"Deposit\",\"Amount deposited\")\n",
    "        \n",
    "        con=sqlite3.connect(database=\"bank.sqlite\")\n",
    "        cur=con.cursor()\n",
    "        from datetime import datetime\n",
    "        dt=str(datetime.now())\n",
    "        cur.execute(\"insert into txn values(?,?,?,?,?)\",(tup[0],dt,amt,\"Credit\",bal))\n",
    "        con.commit()\n",
    "        con.close()\n",
    "        \n",
    "    logout_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Logout\",width=10,command=logout)\n",
    "    logout_btn.place(relx=.89,rely=0)\n",
    "    \n",
    "    lbl_wel=Label(frm,text=f\"Welcome,{tup[1]}\",font=('cambria',12,'bold'),bg='powder blue')\n",
    "    lbl_wel.place(relx=0,rely=0)\n",
    "    \n",
    "    lbl_pic=Label(frm,image=default_pic)\n",
    "    lbl_pic.place(relx=0,rely=.06)\n",
    "    \n",
    "    imgs=os.listdir(\"images\")\n",
    "    \n",
    "    for img in imgs:\n",
    "        if(img.startswith(str(tup[0]))):\n",
    "            pic=ImageTk.PhotoImage(Image.open(f\"images/{img}\").resize((125,140)),master=win)\n",
    "            lbl_pic.configure(image=pic)\n",
    "            lbl_pic.image=pic\n",
    "            \n",
    "    lbl_title=Label(frm,text=\"Deposit Screen\",fg='green',font=('cambria',25,'bold','underline'),bg='powder blue')\n",
    "    lbl_title.pack()\n",
    "    \n",
    "    back_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Back\",width=10, command=back)\n",
    "    back_btn.place(relx=0,rely=.3)\n",
    "    \n",
    "    lbl_amt=Label(frm,text=\"Amount\",font=('cambria',15,'bold'),bg='powder blue')\n",
    "    lbl_amt.place(relx=.3,rely=.2)\n",
    "    \n",
    "    amt_entry=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "    amt_entry.place(relx=.4,rely=.2)\n",
    "    \n",
    "    sub_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Submit\",width=10,command=submit)\n",
    "    sub_btn.place(relx=.89,rely=.84)\n",
    "    \n",
    "    \n",
    "def updateprofile_screen():\n",
    "    frm=Frame(win)\n",
    "    frm.configure(bg=\"powder blue\")\n",
    "    frm.place(x=0,y=100,relwidth=1,relheight=.9)\n",
    "    \n",
    "    def logout():\n",
    "        frm.destroy()\n",
    "        home_screen()  \n",
    "    def back():\n",
    "        frm.destroy()\n",
    "        login_screen()\n",
    "        \n",
    "    def submit():\n",
    "        name=name_entry.get()\n",
    "        pwd=pass_entry.get()\n",
    "        email=email_entry.get()\n",
    "        mob=mob_entry.get()\n",
    "        con=sqlite3.connect(database=\"bank.sqlite\")\n",
    "        cur=con.cursor()\n",
    "        cur.execute(\"update users set name=?,pass=?,email=?,mob=? where acn=?\",(name,pwd,email,mob,tup[0]))\n",
    "        con.commit()\n",
    "        con.close()\n",
    "        messagebox.showinfo(\"Update\",\"Details Updated\")\n",
    "        \n",
    "    logout_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Logout\",width=10,command=logout)\n",
    "    logout_btn.place(relx=.89,rely=0)\n",
    "    \n",
    "    lbl_wel=Label(frm,text=f\"Welcome,{tup[1]}\",font=('cambria',12,'bold'),bg='powder blue')\n",
    "    lbl_wel.place(relx=0,rely=0)\n",
    "    \n",
    "    lbl_pic=Label(frm,image=default_pic)\n",
    "    lbl_pic.place(relx=0,rely=.06)\n",
    "    \n",
    "    imgs=os.listdir(\"images\")\n",
    "    \n",
    "    for img in imgs:\n",
    "        if(img.startswith(str(tup[0]))):\n",
    "            pic=ImageTk.PhotoImage(Image.open(f\"images/{img}\").resize((125,140)),master=win)\n",
    "            lbl_pic.configure(image=pic)\n",
    "            lbl_pic.image=pic\n",
    "    \n",
    "    lbl_title=Label(frm,text=\"Update Profile\",fg='green',font=('cambria',25,'bold','underline'),bg='powder blue')\n",
    "    lbl_title.pack()\n",
    "    \n",
    "    back_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Back\",width=10, command=back)\n",
    "    back_btn.place(relx=0,rely=.3)\n",
    "    \n",
    "    lbl_name=Label(frm,text=\"Name\",font=('cambria',15,'bold'),bg='powder blue')\n",
    "    lbl_name.place(relx=.3,rely=.1)\n",
    "    \n",
    "    name_entry=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "    name_entry.place(relx=.4,rely=.1)\n",
    "    name_entry.insert(0,tup[1])\n",
    "    \n",
    "    lbl_pass=Label(frm,text=\"Pass\",font=('cambria',15,'bold'),bg='powder blue')\n",
    "    lbl_pass.place(relx=.3,rely=.2)\n",
    "    \n",
    "    pass_entry=Entry(frm,font=('cambria',15,'bold'),bd=3,show=\"*\")\n",
    "    pass_entry.place(relx=.4,rely=.2)\n",
    "    pass_entry.insert(0,tup[2])\n",
    "    \n",
    "    lbl_email=Label(frm,text=\"Email\",font=('cambria',15,'bold'),bg='powder blue')\n",
    "    lbl_email.place(relx=.3,rely=.3)\n",
    "    \n",
    "    email_entry=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "    email_entry.place(relx=.4,rely=.3)\n",
    "    email_entry.insert(0,tup[4])\n",
    "    \n",
    "    lbl_mob=Label(frm,text=\"Mob\",font=('cambria',15,'bold'),bg='powder blue')\n",
    "    lbl_mob.place(relx=.3,rely=.4)\n",
    "    \n",
    "    mob_entry=Entry(frm,font=('cambria',15,'bold'),bd=3)\n",
    "    mob_entry.place(relx=.4,rely=.4)\n",
    "    mob_entry.insert(0,tup[3])\n",
    "    \n",
    "    sub_btn=Button(frm,font=('cambria',15,'bold'),bd=5,text=\"Submit\",width=10,command=submit)\n",
    "    sub_btn.place(relx=.89,rely=.84)\n",
    "    \n",
    "\n",
    "    \n",
    "def txnhistory_screen():\n",
    "    frm=Frame(win)\n",
    "    frm.configure(bg=\"powder blue\")\n",
    "    frm.place(x=0,y=100,relwidth=1,relheight=.9)\n",
    "    \n",
    "    def logout():\n",
    "        frm.destroy()\n",
    "        home_screen()  \n",
    "    def back():\n",
    "        frm.destroy()\n",
    "        login_screen()\n",
    "        \n",
    "    logout_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Logout\",width=10,command=logout)\n",
    "    logout_btn.place(relx=.89,rely=0)\n",
    "    \n",
    "    lbl_wel=Label(frm,text=f\"Welcome,{tup[1]}\",font=('cambria',12,'bold'),bg='powder blue')\n",
    "    lbl_wel.place(relx=0,rely=0)\n",
    "    \n",
    "    lbl_pic=Label(frm,image=default_pic)\n",
    "    lbl_pic.place(relx=0,rely=.06)\n",
    "    \n",
    "    imgs=os.listdir(\"images\")\n",
    "    \n",
    "    for img in imgs:\n",
    "        if(img.startswith(str(tup[0]))):\n",
    "            pic=ImageTk.PhotoImage(Image.open(f\"images/{img}\").resize((125,140)),master=win)\n",
    "            lbl_pic.configure(image=pic)\n",
    "            lbl_pic.image=pic\n",
    "    \n",
    "    lbl_title=Label(frm,text=\"Txn Details\",fg='green',font=('cambria',25,'bold','underline'),bg='powder blue')\n",
    "    lbl_title.pack()\n",
    "    \n",
    "    back_btn=Button(frm,font=('cambria',15,'bold'),bd=3,text=\"Back\",width=10, command=back)\n",
    "    back_btn.place(relx=0,rely=.3)\n",
    "    \n",
    "    con=sqlite3.connect(database=\"bank.sqlite\")\n",
    "    cur=con.cursor()\n",
    "    cur.execute(\"select * from txn where acn=?\",(tup[0],))\n",
    "    txn_data=\"ACN \\t\\tDate_time \\t\\tAmt \\t\\tTxn_Type \\t\\tUpdate Bal\\n\\n\"\n",
    "    all_data=cur.fetchall()\n",
    "    \n",
    "    for t in all_data:\n",
    "        t=map(str,t)\n",
    "        t1=\"  \".join(t)\n",
    "        txn_data=txn_data+t1+\"\\n\\n\"\n",
    "    lbl_txndata=Label(frm,text=txn_data,font=('cambria',15),bg=\"powder blue\",fg=\"navy blue\")\n",
    "    lbl_txndata.place(relx=.2,rely=.2)\n",
    "    \n",
    "    con.close()\n",
    "home_screen()\n",
    "win.mainloop()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
